Creating numpy arrays:


1.From python list

In [1]:
import numpy as np
arr=([1,2,3]) #1d array
print(arr)

[1, 2, 3]


In [2]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [3]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.random.rand(3,3)

array([[0.15613644, 0.15878429, 0.50847529],
       [0.54633886, 0.07860291, 0.68805988],
       [0.71379311, 0.55447284, 0.20691925]])

In [5]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
np.random.randint(-10,3)

2

In [7]:
arr=([1,2,3],[4,5,6],[7,8,9])

In [8]:
print(type(arr))

<class 'tuple'>


In [9]:
arr=np.array(arr)

In [10]:
print(arr.shape)

(3, 3)


In [11]:
print(arr.dtype)

int64


In [12]:
print(arr[0,1])

2


In [18]:
print(arr[1, (0,1)])

[4 5]


In [23]:
print(arr[1, (arr[1]>5)])

[6]


In [29]:
a=np.array([[1,2], [3,4]])
b=np.array([[5,6], [7,8]])

In [30]:
print(np.dot(a,b))

[[19 22]
 [43 50]]


In [31]:
print(np.matmul(a,b))

[[19 22]
 [43 50]]


In [32]:
print(np.multiply(a,b))

[[ 5 12]
 [21 32]]


In [39]:
print(np.reshape(a[1],(-1)))

[3 4]


In [41]:
print(a.T)#Transpose as it is swaping rows and columns

[[1 3]
 [2 4]]


In [44]:
a=np.array([[1,2,3,4]])
b=np.array([[1],[2],[3]])
print(a+b)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


In [50]:
arr = np.array([[3, 1, 2], [9, 7, 8]])
print(np.sort(arr))

[[1 2 3]
 [7 8 9]]


In [52]:
from numpy.linalg import det
a=np.array([[1,2],[3,4]])
print(det(a))

-2.0000000000000004


In [53]:
from numpy.linalg import inv
print(inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [54]:
from numpy.linalg import eig
print(eig(a))

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
